import { UserRole } from "../interfaces/roles/roles.interface";

export enum Permission {
    COMPANY_READ = 'COMPANY_READ',
    COMPANY_WRITE = 'COMPANY_WRITE',
    USER_READ = 'USER_READ',
    USER_WRITE = 'USER_WRITE',
    RANCH_READ = 'RANCH_READ',
    RANCH_WRITE = 'RANCH_WRITE',
    MEMBERSHIP_READ = 'MEMBERSHIP_READ',
    MEMBERSHIP_WRITE = 'MEMBERSHIP_WRITE',
    ANIMAL_READ = 'ANIMAL_READ',
    ANIMAL_WRITE = 'ANIMAL_WRITE',
    ANIMAL_WORK_SESSION_READ = 'ANIMAL_WORK_SESSION_READ',
    ANIMAL_WORK_SESSION_WRITE = 'ANIMAL_WORK_SESSION_WRITE',
    REFERENCE_SAMPLE_READ = 'REFERENCE_SAMPLE_READ',
    REFERENCE_SAMPLE_WRITE = 'REFERENCE_SAMPLE_WRITE',
}

export const PERMISSION_ROLE_MAP: Record<Permission, UserRole[]> = {
    [Permission.COMPANY_READ]: [UserRole.SAAS_OWNER],
    [Permission.COMPANY_WRITE]: [UserRole.SAAS_OWNER],
    [Permission.USER_READ]: [UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.USER_WRITE]: [UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.RANCH_READ]: [UserRole.USER, UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.RANCH_WRITE]: [UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.MEMBERSHIP_READ]: [UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.MEMBERSHIP_WRITE]: [UserRole.SAAS_OWNER],
    [Permission.ANIMAL_READ]: [UserRole.USER, UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.ANIMAL_WRITE]: [UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.ANIMAL_WORK_SESSION_READ]: [UserRole.USER, UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.ANIMAL_WORK_SESSION_WRITE]: [UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.REFERENCE_SAMPLE_READ]: [UserRole.USER, UserRole.HEALTHCARE_STAFF, UserRole.SUPERVISOR, UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
    [Permission.REFERENCE_SAMPLE_WRITE]: [UserRole.ADMINISTRATOR, UserRole.SAAS_OWNER],
};
